name: Codespell CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  codespell:
    name: Codespell CI

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: sudo apt update -y && sudo apt install -y codespell

      - name: Run codespell
        run: codespell
