name: "Markdown link CI"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ main ]
    paths:
      - .github/workflows/markdown-link.yml
      - '**.md'

  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/markdown-link.yml
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
